-- COALESCE
SELECT COALESCE(NULL, 0);  -- 0
SELECT COALESCE(NULL, NULL); -- NULL;
SELECT COALESCE('AISHU',1,NULL, NULL); 
SELECT COALESCE(1,NULL, NULL);

-- GREATEST/LEAST
SELECT GREATEST(10, 20, 30),  -- 30
       LEAST(10, 20, 30); -- 10

SELECT GREATEST(10, null, 30),  -- null
       LEAST(10, null , 30); -- null

-- ISNULL
SELECT ISNULL(NULL); -- 1    
SELECT ISNULL(1);  -- 0
SELECT ISNULL(1 + NULL); -- 1;
SELECT ISNULL(1 / 0 ); -- 1;

SELECT * FROM student WHERE ISNULL(name);
SELECT distinct(NAME) FROM student;
SELECT group_concat('A','R')