#COLUMN LEVEL FILTERING

SELECT * FROM customers;
SELECT first_name,city  FROM customers;
SELECT DISTINCT cust_id FROM customers;
SELECT COUNT(*) AS total_customers FROM Customers;
SELECT * FROM customers LIMIT 3;

-- ============================================

SELECT * FROM INFORMATION_SCHEMA.TABLES;  # meta data  -- tables available in server

# 1. List all databases
SELECT SCHEMA_NAME 
FROM INFORMATION_SCHEMA.SCHEMATA;
# 2. List all tables in databases
SELECT TABLE_NAME 
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'customerdb';
# 3. Get columns of a table
SELECT COLUMN_NAME, DATA_TYPE, IS_NULLABLE 
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'Customers'
  AND TABLE_SCHEMA ='customerdb';
  
# 4.find PK
SELECT TABLE_NAME, COLUMN_NAME
FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE
WHERE CONSTRAINT_NAME = 'PRIMARY'
  AND TABLE_SCHEMA = 'customerdb';

# 5.find FK
SELECT CONSTRAINT_NAME, TABLE_NAME, COLUMN_NAME, REFERENCED_TABLE_NAME, REFERENCED_COLUMN_NAME
FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE
WHERE REFERENCED_TABLE_SCHEMA =  'customerdb';

# 6. Find user privileges
SELECT * 
FROM INFORMATION_SCHEMA.USER_PRIVILEGES;